import { createServerFn } from '@tanstack/react-start';
import { z } from 'zod';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
import { supabaseAdmin } from '@/integrations/supabase/client.server';

const schema = z.object({
  // The proposal must carry the client's id (when the client already exists)
  // and the client's email (always required to send the invite).
  clientId: z.string().uuid().optional().nullable(),
  email: z.string().trim().email().max(255),
  name: z.string().trim().min(1).max(255).optional().nullable(),
});

async function ensureCallerIsAdmin(userId: string) {
  const { data, error } = await supabaseAdmin
    .from('user_roles')
    .select('role')
    .eq('user_id', userId);
  if (error) throw new Error('Falha ao verificar permissões.');
  const isAdmin = (data ?? []).some((r) => r.role === 'admin');
  if (!isAdmin) throw new Error('Acesso negado. Apenas administradores podem executar esta ação.');
}

/**
 * Automation: when a new proposal is attached in the app, check whether the
 * client associated with the proposal already has a registration. If the
 * client is NEW, generate a Supabase Auth invite link and email it to the
 * client so they can register and access the Dicoon Seguros app.
 *
 * - The invite email is sent through Supabase Auth's email service.
 * - The invite link is generated by Supabase Auth (inviteUserByEmail).
 * - Existing clients are detected by clientId (profile) or by email
 *   (profiles + auth users), making the call idempotent — no duplicate invites.
 */
export const inviteClientFromProposal = createServerFn({ method: 'POST' })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => schema.parse(input))
  .handler(async ({ data, context }) => {
    await ensureCallerIsAdmin(context.userId);

    const email = data.email.toLowerCase();
    const name = data.name?.trim().toUpperCase() || email.split('@')[0].toUpperCase();

    // 1. Is this an existing client? Check by clientId first, then by email.
    if (data.clientId) {
      const { data: byId } = await supabaseAdmin
        .from('profiles')
        .select('user_id')
        .eq('user_id', data.clientId)
        .maybeSingle();
      if (byId) {
        return { invited: false, alreadyRegistered: true as const, reason: 'profile_by_id' };
      }
    }

    const { data: byEmail } = await supabaseAdmin
      .from('profiles')
      .select('user_id')
      .eq('email', email)
      .maybeSingle();
    if (byEmail) {
      return { invited: false, alreadyRegistered: true as const, reason: 'profile_by_email' };
    }

    // Also check the auth users directory (handles invited-but-no-profile cases).
    const list = await supabaseAdmin.auth.admin.listUsers({ page: 1, perPage: 200 });
    const existingAuthUser = list.data.users.find((u) => u.email?.toLowerCase() === email);
    if (existingAuthUser) {
      return { invited: false, alreadyRegistered: true as const, reason: 'auth_user' };
    }

    // 2. NEW client → send the Supabase Auth invite email with a registration link.
    const siteUrl =
      process.env.SITE_URL ||
      process.env.PUBLIC_SITE_URL ||
      'https://dicoonseguros-portal.lovable.app';
    const redirectTo = `${siteUrl.replace(/\/$/, '')}/reset-password`;

    const inviteRes = await supabaseAdmin.auth.admin.inviteUserByEmail(email, {
      data: { name },
      redirectTo,
    });

    if (inviteRes.error) {
      const msg = inviteRes.error.message?.toLowerCase() ?? '';
      if (msg.includes('already') || msg.includes('registered') || msg.includes('exists')) {
        return { invited: false, alreadyRegistered: true as const, reason: 'invite_exists' };
      }
      console.error('inviteClientFromProposal failed:', inviteRes.error);
      throw new Error('Não foi possível enviar o convite por e-mail. Tente novamente.');
    }

    const newUserId = inviteRes.data.user?.id ?? null;

    // Seed a profile so the client appears in the system right away.
    if (newUserId) {
      await supabaseAdmin
        .from('profiles')
        .upsert(
          {
            user_id: newUserId,
            email,
            name,
            status: 'pending',
            updated_at: new Date().toISOString(),
          },
          { onConflict: 'user_id' },
        );
    }

    return { invited: true as const, alreadyRegistered: false, userId: newUserId };
  });
