/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RenovacoesRouteImport } from './routes/renovacoes'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as PropostaRouteImport } from './routes/proposta'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as NovaCotacaoRouteImport } from './routes/nova-cotacao'
import { Route as MulticalculoRouteImport } from './routes/multicalculo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DashboardClienteRouteImport } from './routes/dashboard-cliente'
import { Route as DashboardAdminRouteImport } from './routes/dashboard-admin'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExtractPolicyRouteImport } from './routes/api/extract-policy'
import { Route as AdminImportarApoliceRouteImport } from './routes/admin.importar-apolice'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovacoesRoute = RenovacoesRouteImport.update({
  id: '/renovacoes',
  path: '/renovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaRoute = PropostaRouteImport.update({
  id: '/proposta',
  path: '/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaCotacaoRoute = NovaCotacaoRouteImport.update({
  id: '/nova-cotacao',
  path: '/nova-cotacao',
  getParentRoute: () => rootRouteImport,
} as any)
const MulticalculoRoute = MulticalculoRouteImport.update({
  id: '/multicalculo',
  path: '/multicalculo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClienteRoute = DashboardClienteRouteImport.update({
  id: '/dashboard-cliente',
  path: '/dashboard-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard-admin',
  path: '/dashboard-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractPolicyRoute = ApiExtractPolicyRouteImport.update({
  id: '/api/extract-policy',
  path: '/api/extract-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportarApoliceRoute = AdminImportarApoliceRouteImport.update({
  id: '/importar-apolice',
  path: '/importar-apolice',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/comparador': typeof ComparadorRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-cliente': typeof DashboardClienteRoute
  '/documentos': typeof DocumentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/multicalculo': typeof MulticalculoRoute
  '/nova-cotacao': typeof NovaCotacaoRoute
  '/pipeline': typeof PipelineRoute
  '/proposta': typeof PropostaRoute
  '/propostas': typeof PropostasRoute
  '/renovacoes': typeof RenovacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timeline': typeof TimelineRoute
  '/admin/importar-apolice': typeof AdminImportarApoliceRoute
  '/api/extract-policy': typeof ApiExtractPolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/comparador': typeof ComparadorRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-cliente': typeof DashboardClienteRoute
  '/documentos': typeof DocumentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/multicalculo': typeof MulticalculoRoute
  '/nova-cotacao': typeof NovaCotacaoRoute
  '/pipeline': typeof PipelineRoute
  '/proposta': typeof PropostaRoute
  '/propostas': typeof PropostasRoute
  '/renovacoes': typeof RenovacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timeline': typeof TimelineRoute
  '/admin/importar-apolice': typeof AdminImportarApoliceRoute
  '/api/extract-policy': typeof ApiExtractPolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/comparador': typeof ComparadorRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-cliente': typeof DashboardClienteRoute
  '/documentos': typeof DocumentosRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/multicalculo': typeof MulticalculoRoute
  '/nova-cotacao': typeof NovaCotacaoRoute
  '/pipeline': typeof PipelineRoute
  '/proposta': typeof PropostaRoute
  '/propostas': typeof PropostasRoute
  '/renovacoes': typeof RenovacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/timeline': typeof TimelineRoute
  '/admin/importar-apolice': typeof AdminImportarApoliceRoute
  '/api/extract-policy': typeof ApiExtractPolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clientes'
    | '/comparador'
    | '/dashboard-admin'
    | '/dashboard-cliente'
    | '/documentos'
    | '/leads'
    | '/login'
    | '/multicalculo'
    | '/nova-cotacao'
    | '/pipeline'
    | '/proposta'
    | '/propostas'
    | '/renovacoes'
    | '/reset-password'
    | '/timeline'
    | '/admin/importar-apolice'
    | '/api/extract-policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clientes'
    | '/comparador'
    | '/dashboard-admin'
    | '/dashboard-cliente'
    | '/documentos'
    | '/leads'
    | '/login'
    | '/multicalculo'
    | '/nova-cotacao'
    | '/pipeline'
    | '/proposta'
    | '/propostas'
    | '/renovacoes'
    | '/reset-password'
    | '/timeline'
    | '/admin/importar-apolice'
    | '/api/extract-policy'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clientes'
    | '/comparador'
    | '/dashboard-admin'
    | '/dashboard-cliente'
    | '/documentos'
    | '/leads'
    | '/login'
    | '/multicalculo'
    | '/nova-cotacao'
    | '/pipeline'
    | '/proposta'
    | '/propostas'
    | '/renovacoes'
    | '/reset-password'
    | '/timeline'
    | '/admin/importar-apolice'
    | '/api/extract-policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  ComparadorRoute: typeof ComparadorRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardClienteRoute: typeof DashboardClienteRoute
  DocumentosRoute: typeof DocumentosRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MulticalculoRoute: typeof MulticalculoRoute
  NovaCotacaoRoute: typeof NovaCotacaoRoute
  PipelineRoute: typeof PipelineRoute
  PropostaRoute: typeof PropostaRoute
  PropostasRoute: typeof PropostasRoute
  RenovacoesRoute: typeof RenovacoesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TimelineRoute: typeof TimelineRoute
  ApiExtractPolicyRoute: typeof ApiExtractPolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovacoes': {
      id: '/renovacoes'
      path: '/renovacoes'
      fullPath: '/renovacoes'
      preLoaderRoute: typeof RenovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta': {
      id: '/proposta'
      path: '/proposta'
      fullPath: '/proposta'
      preLoaderRoute: typeof PropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-cotacao': {
      id: '/nova-cotacao'
      path: '/nova-cotacao'
      fullPath: '/nova-cotacao'
      preLoaderRoute: typeof NovaCotacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multicalculo': {
      id: '/multicalculo'
      path: '/multicalculo'
      fullPath: '/multicalculo'
      preLoaderRoute: typeof MulticalculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-cliente': {
      id: '/dashboard-cliente'
      path: '/dashboard-cliente'
      fullPath: '/dashboard-cliente'
      preLoaderRoute: typeof DashboardClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-admin': {
      id: '/dashboard-admin'
      path: '/dashboard-admin'
      fullPath: '/dashboard-admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-policy': {
      id: '/api/extract-policy'
      path: '/api/extract-policy'
      fullPath: '/api/extract-policy'
      preLoaderRoute: typeof ApiExtractPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/importar-apolice': {
      id: '/admin/importar-apolice'
      path: '/importar-apolice'
      fullPath: '/admin/importar-apolice'
      preLoaderRoute: typeof AdminImportarApoliceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminImportarApoliceRoute: typeof AdminImportarApoliceRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportarApoliceRoute: AdminImportarApoliceRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientesRoute: ClientesRoute,
  ComparadorRoute: ComparadorRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardClienteRoute: DashboardClienteRoute,
  DocumentosRoute: DocumentosRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MulticalculoRoute: MulticalculoRoute,
  NovaCotacaoRoute: NovaCotacaoRoute,
  PipelineRoute: PipelineRoute,
  PropostaRoute: PropostaRoute,
  PropostasRoute: PropostasRoute,
  RenovacoesRoute: RenovacoesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TimelineRoute: TimelineRoute,
  ApiExtractPolicyRoute: ApiExtractPolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
